# Generated by Django 5.0.1 on 2024-01-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_id",
            field=models.CharField(max_length=20, unique=True, verbose_name="user id"),
        ),
    ]
